"""Uncertainty-preserving candidate fallback when faster-whisper is absent."""

from typing import Any


def fallback_candidates(
    segment: dict,
    decode_configs: list[dict[str, Any]],
    speaker_hypotheses: list[str] | None = None,
) -> list[dict]:
    """Return explicit uncertainty-preserving candidates when ASR backend is absent."""
    segment_id = str(segment.get("segment_id") or segment.get("evidence_id") or "segment")
    text = str(segment.get("text", "")).strip()
    if not text:
        text = "[high-overlap transcript candidate pending ASR decode]"

    return [
        {
            "candidate_id": f"{segment_id}_c{index}",
            "speaker": _speaker_hypothesis(index, speaker_hypotheses),
            "text": text,
            "confidence": round(max(0.0, 0.62 - 0.07 * (index - 1)), 3),
            "uncertainty_note": _decode_note(config, backend="fallback"),
            "decode_config": {
                "beam_size": int(config["beam_size"]),
                "temperature": float(config["temperature"]),
                "language": config.get("language") or "auto",
            },
        }
        for index, config in enumerate(decode_configs, start=1)
    ]


def _speaker_hypothesis(index: int, speakers: list[str] | None = None) -> str:
    """Use diarization-supported speakers instead of inventing identities."""
    normalized = [str(speaker) for speaker in speakers or [] if str(speaker).strip()]
    if not normalized:
        return "UNKNOWN"
    return normalized[(index - 1) % len(normalized)]


def _decode_note(config: dict[str, Any], backend: str) -> str:
    """Human-readable uncertainty note for one candidate."""
    language = config.get("language") or "auto"
    return (
        "High-overlap segment; speaker attribution is uncertain. "
        f"Candidate generated by {backend} decode "
        f"(beam_size={config['beam_size']}, temperature={config['temperature']}, language={language})."
    )


__all__ = ["fallback_candidates"]
